project_name: go-cat
builds:
  - main: ./cmd/go-cat
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
    - sorcero/go-cat


release:
  gitlab:
    owner: ""
    name: 30584689

nfpms:
- maintainer: Sorcero
  description: Keep track of your infrastructure across multiple clouds.
  homepage: https://gitlab.com/sorcero/community/go-cat
  license: MPL-2.0
  formats:
  - deb
  - rpm
  - apk

